#!/bin/sh
#copy this file to .git/hooks to enable uwsgi emperor reload on push
#TODO: check if requirements.txt has been modified. if so, regenerate venv
# python3 venv %{VENV_ROOT}/project;
#{VENV_ROOT}/project/bin/pip install --upgrade pip
#{VENV_ROOT}/project/bin/pip install -r ../requirements.txt
echo "Touching config to reload the app"
touch ../vassal.ini
echo "Done!"
